# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_title',
            new_name='title',
        ),
    ]
