# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170713_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'Concert'), ('Festival', 'Festival'), ('Civics', 'Civics'), ('Food', 'Food'), ('Misc', 'Misc')], default='Misc', max_length=50),
        ),
    ]
