# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('CON', 'Concert'), ('FEST', 'Festival'), ('MISC', 'Misc')], default='misc', max_length=50),
        ),
    ]
