# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170719_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'CON'), ('Festival', 'FEST'), ('Miscellaneous', 'MISC')], default='misc', max_length=50),
        ),
    ]
