# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170720_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'CON'), ('Festival', 'FEST'), ('Kids', 'KIDS'), ('Miscellaneous', 'MISC')], default='misc', max_length=50),
        ),
    ]
