# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170721_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Concert', 'CON'), ('Festival', 'FEST'), ('Kids', 'KIDS'), ('Miscellaneous', 'MISC')], default='Miscellaneous', max_length=50),
        ),
    ]
