# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170721_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.CharField(default='Hodor', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
