# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170811_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(default='Hodor'),
        ),
    ]
