# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170811_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_site',
            field=models.URLField(default='#'),
        ),
    ]
