# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(default='100 char max', max_length=100)),
                ('website', models.URLField(default='#')),
                ('image', models.URLField(default='#')),
                ('days', models.CharField(max_length=25)),
                ('isOnWeekend', models.BooleanField(default=True)),
            ],
        ),
    ]
